INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(1, 'Stephany', 'Adams', 'Johnson', {ts '1980-01-20'}, {ts '2011-01-01'}, 0);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(2, 'Lisa', null, 'Scott', {ts '1990-11-14'}, {ts '2018-02-05'}, 0);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(3, 'Ashley', null, 'Parker', {ts '1981-10-14'}, {ts '2011-11-01'}, 1);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(4, 'Dylan', 'Russell', 'Harris', {ts '1988-10-01'}, {ts '2017-06-21'}, 1);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(5, 'Willy', 'Torres', 'Thompson', {ts '1986-07-10'}, {ts '2016-01-21'}, 0);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(6, 'Jimmy', null, 'Moore', {ts '1975-03-04'}, {ts '2015-07-31'}, 0);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(7, 'Xayane', null, 'Russell', {ts '1985-10-14'}, {ts '2018-05-01'}, 1);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(8, 'Mary', null, 'Adams', {ts '1979-12-02'}, {ts '2012-11-11'}, 1);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(9, 'Bruce', 'Jones', 'Torres', {ts '1986-12-14'}, {ts '2011-12-15'}, 0);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME, DATE_OF_BIRTH, DATE_OF_EMPLOYMENT, STATUS)
VALUES(10, 'Franklin', null, 'Jones', {ts '1984-12-12'}, {ts '2010-01-20'}, 0);